import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../lib/ThemeProvider";
import Header from "@/components/Header";
import { ChatContextProvider } from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Marian - Assistant",
  description: "Generated by create next api",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class">
        <ChatContextProvider>
          <body className={inter.className}>{children}</body>
        </ChatContextProvider>
      </ThemeProvider>
    </html>
  );
}
